### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/aws-sns#1]
Ping me when you're done with the code, tests and readme. I'll do a little code review and publish your package on Packagist.

**Comment by clarkeash** [comment]
@themsaid @freekmurze Is this being worked on? I'd be happy to take it on if you like.

**Comment by themsaid** [comment]
@arcdigital Are you still working on this?

**Comment by mnfgul** [comment]
@themsaid I have already developed aws-sns channel as we badly needed it. I would like to propose it to be used here. Please have a look at it here [https://github.com/mnfgul/skeleton](https://github.com/mnfgul/skeleton)

**Comment by borger** [comment]
Hello! Do we have an official package yet? If not, is there anyway I could help?

**Comment by urukalo** [comment]
what is wrong with this package by @mnfgul ...  why it stay here more than one year? @themsaid

**Comment by eberkund** [comment]
Bump, what's happening here?

**Comment by atymic** [comment]
Hey all.

Is anyone still interested in working on a channel?
Sorry for the delays, I'll be around to code review now :)

**Comment by clemblanco** [comment]
Happy to help.

**Comment by claudsonm** [comment]
I wasn't able to make the PR directly to this repo. So I opened the PR as instructed in https://github.com/laravel-notification-channels/channels.

The PR is here: https://github.com/laravel-notification-channels/channels/pull/81

Could you check it out @atymic ?

**Comment by atymic** [comment]
Channel Live 🎉
