### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/aws-sns#10]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by claudsonm** [comment]
PR #11 merged. Tagging a new release soon.

**Comment by claudsonm** [comment]
Done! Version `1.2.0` is live!

**Comment by atymic** [comment]
Thanks :D
