### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/aws-sns#2]
- [x] Code Review
- [x] Add @claudsonm as repo admin
- [x] Add @claudsonm to github org
- [x] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by claudsonm** [comment]
PR was sent https://github.com/laravel-notification-channels/aws-sns/pull/3

No idea why Travis is blowing up with Mockery dependencies on vendor files.

**Comment by atymic** [comment]
Wesite PR: https://github.com/laravel-notification-channels/website/pull/16

**Comment by claudsonm** [comment]
PR https://github.com/laravel-notification-channels/aws-sns/pull/3 looks good. Anything else I should do?

**Comment by atymic** [comment]
Sweet, i've merged the PR for you and added to packagist.
When you tag the first version we're good to go (i'll merge the website PR then as well)

**Comment by atymic** [comment]
Website PR merged :)

We're live 🎉
