### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by arctic-ice-cool** [laravel-notification-channels/aws-sns#20]
Hello,

Do we have an ETA for Laravel 9 with this package? Is it held up by the AWS Guzzle issue?

**Comment by claudsonm** [comment]
Last time I checked, the problem with the AWS SDK was still a thing, but it could be managed by installing the package with the flag `--update-with-dependencies`.

The upgrade is usually pretty easy. Just need to bump the supported laravel version in the `composer.json`. But it needs to be tested. I'll take a look when I have some time. Add some Github Actions to test this automatically would be good too.

Also, PRs are welcome.

**Comment by arctic-ice-cool** [comment]
Hello,

Yes - I've bumped it and tested it and it works fine.

Is it just a case of amending the composer.json now, or would you look for any additional new tests first?

Thanks

**Comment by repat** [comment]
@claudsonm any progress on this? The PR looks good :)

**Comment by claudsonm** [comment]
The PR #21 is merged.

Will be released in version 1.4.0 latter today.
