### ISSUE TITLE
Entity ID and Template ID

### ISSUE THREAD

**Issue by yogesh-jgu** [laravel-notification-channels/aws-sns#22]
Dear Team,

How can I specify entity Id and template Id to send the message from aws?

Thanks,

**Comment by claudsonm** [comment]
Hi there,

Take a look at the [Available SnsMessage methods](https://github.com/laravel-notification-channels/aws-sns#available-snsmessage-methods) section in the README. I think it is what you are looking for. There are examples in the Usage section.
