### ISSUE TITLE
Laravel Vapor compatability

### ISSUE THREAD

**Issue by olivervo** [laravel-notification-channels/aws-sns#23]
Having trouble getting the package to work on Laravel Vapor using `Laravel 9.30` and `aws/aws-sdk-php 3.235`. My Vapor site is using the runtime `php-8.1:al2`. In local env SMS are sent are expected, however on a vapor site there is no record of any attempt to send a message in AWS (not logged as success or failure). Nothing in site logs either. 

Steps taken without success:
- Tried on two separate vapor sites
- Tried dispatching notification synchronously (not queuing)
- Tried switching to Docker runtime using the following script since SimpleXML is require according to [AWS docs](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_requirements.html#requirements) (even though SimpleXML should be enabled by default).

```
environment.Dockerfile

FROM laravelphp/vapor:php81

# Add SimpleXML PHP extension
RUN apk --update add php8-simplexml
RUN docker-php-ext-install simplexml
```

**Comment by claudsonm** [comment]
It looks like your messages are not being delivered. Take a look at this comment on another similar issue and see if you can get better debug results.
https://github.com/laravel-notification-channels/aws-sns/issues/9#issuecomment-689538532

**Comment by olivervo** [comment]
Laravel Vapor does not have permission to send SMS via SNS in AWS by default. 

Added to the docs along with exception handling in PR #24
